# Site settings
title:  A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "http://smartideasinc.github.io"

# Build settings
baseurl: /cactus-jekyll-theme/
markdown: kramdown
gems:
      - jekyll-sitemap
